name: flutter_app_template_cli
description: CLI to generate a Flutter monorepo workspace with apps/ and packages/.
version: 0.1.4
homepage: https://github.com/mixin27/flutter_app_template_cli
repository: https://github.com/mixin27/flutter_app_template_cli
issue_tracker: https://github.com/mixin27/flutter_app_template_cli/issues
topics:
  - flutter
  - cli
  - template
  - monorepo
  - scaffold

environment:
  sdk: ^3.11.1

dependencies:
  args: ^2.5.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  flutter_app_template_cli: flutter_app_template_cli
