name: flutter_app_template_cli
description: CLI to generate a Flutter monorepo workspace with apps/ and packages/.
version: 0.1.0

environment:
  sdk: ^3.11.1

dependencies:
  args: ^2.5.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
